### PR TITLE
Add Stack support and upgrade to lts-3.16.

### PR DESCRIPTION
**Pull request by patrickt**
Certain dependencies (most notably HTF) were limiting it to lts-2.22. My preferred way to deal with this is to remove all constraints in the .cabal file and let stack deal with dependencies, but if you'd like me to restore some of the dependencies, let me know.

### CODE REVIEW

**Comment by nikita-volkov** [comment]
It happens so that I'm one of the strong opposers to open dependency bounds. Also not am I thrilled about the prospect of maintaining another configuration file. So I'm afraid I can't merge this.

Stack however should already be able to support this library. After all, HTF is only a test dependency. Probably this should be reported to Stackage.

**Comment by patrickt** [comment]
Re. dependency bounds: that's perfectly fair. Would you be amenable to bumping up the HTF dependency to 0.13 instead? If that lands, stack will know what to do, and you won't have to provide a maintain a stack.yaml file. I'd be happy to close this and make that change in another PR if so.

(n.b.: I'm not sure how much good 'reporting to Stackage' would do in this situation: Stackage wants to build and run every test possible, as it uses tests to attempt to pin down regressions between versions.

**Comment by nikita-volkov** [comment]
>  Would you be amenable to bumping up the HTF dependency to 0.13 instead? If that lands, stack will know what to do, and you won't have to provide a maintain a stack.yaml file. I'd be happy to close this and make that change in another PR if so.

Sure!

**Comment by patrickt** [comment]
Thanks! Closing this.

**Pull request closed without merging**
